version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file : 
      - .env